spring:
  application:
    name: user-service

  datasource:
    url: jdbc:mysql://localhost:3306/test
    username: root
    password: test
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

eureka:
  client:
    service-url:
      defaultZone: http://server:19090/eureka/

server:
  port: 19091
