services:
  server:
    build:
      dockerfile: Dockerfile
      args:
        - FILE_DIRECTORY=./server
    image: $ECR_REGISTRY/$ECR_NAMESPACE/server

  gateway:
    build:
      dockerfile: Dockerfile
      args:
        - FILE_DIRECTORY=./gateway
    image: $ECR_REGISTRY/$ECR_NAMESPACE/gateway
    ports:
      - "8080:8080"

  user:
    build:
      dockerfile: Dockerfile
      args:
        - FILE_DIRECTORY=./user
    image: $ECR_REGISTRY/$ECR_NAMESPACE/user

  company:
    build:
      dockerfile: Dockerfile
      args:
        - FILE_DIRECTORY=./company
    image: $ECR_REGISTRY/$ECR_NAMESPACE/company

  order:
    build:
      dockerfile: Dockerfile
      args:
        - FILE_DIRECTORY=./order
    image: $ECR_REGISTRY/$ECR_NAMESPACE/order

  product:
    build:
      dockerfile: Dockerfile
      args:
        - FILE_DIRECTORY=./product
    image: $ECR_REGISTRY/$ECR_NAMESPACE/product